Bump version to 3.3.6 and fix Firebase dSYM submission
The upload-symbols command has been moved to Archive post-actions (in scheme) because there doesn't seem to be an easier way to access the location for the current archive. Kept getting:

error: Could not complete submission of dSYM at /Users/ep/Library/Developer/Xcode/DerivedData/Simplified-gbyafiwhnvulxkbqanqolsoukujy/Build/Intermediates.noindex/ArchiveIntermediates/Simplified/BuildProductsPath/Release-iphoneos/SimplyE.app.dSYM: Error Domain=com.crashlytics.mac.error-domain.process-dsym Code=3 "File no longer exists at (null)" UserInfo={NSLocalizedFailureReason=File no longer exists at (null)}